SP_ASPNET_1/SP_ASPNET_1/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SP_ASPNET_1.Models
{
    public class Author
    {
        public int AuthorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }

        public override string ToString()
        {
            return $"{this.Name} {this.Surname}";
        }
    }
}

SP_ASPNET_1/SP_ASPNET_1/Models/BlogPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SP_ASPNET_1.Models
{
    public class BlogPost
    {
        public int BlogPostID { get; set; }
        public string Title { get; set; }
        public Author Author { get; set; }
        public DateTime DateTime { get; set; }
        public string Content { get; set; }
        public string ImageUrl { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/Models/ProductItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SP_ASPNET_1.Models
{
    public class ProductItem
    {
        public int ProductItemID { get; set; }
        public string ImageURL { get; set; }
        public string ImageAlt { get; set; }
        public string Title { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/Models/ProductLine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace SP_ASPNET_1.Models
{
    public class ProductLine
    {
        public int ProductLineID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public ICollection<ProductItem> ProductItems { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/ViewModels/BlogIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SP_ASPNET_1.Models;

namespace SP_ASPNET_1.ViewModels
{
    public class BlogIndexViewModel
    {
        public IEnumerable<BlogPost> BlogPosts { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/ViewModels/BlogSinglePostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SP_ASPNET_1.Models;

namespace SP_ASPNET_1.ViewModels
{
    public class BlogSinglePostViewModel : IBlogViewModel
    {
        public BlogPost BlogPost { get; set; }
        public BlogPost RecentBlogPost { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/ViewModels/HomeProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SP_ASPNET_1.Models;

namespace SP_ASPNET_1.ViewModels
{
    public class HomeProductViewModel
    {
        public IEnumerable<ProductLine> ProductLines { get; set; }
    }
}

SP_ASPNET_1/SP_ASPNET_1/ViewModels/IBlogViewModel.cs
using SP_ASPNET_1.Models;

interface IBlogViewModel
{
    BlogPost RecentBlogPost { get; set; }
}

SP_ASPNET_1/SP_ASPNET_1/Controllers/BlogPostController.cs
using SP_ASPNET_1.DbFiles.Operations;
using SP_ASPNET_1.Models;
using SP_ASPNET_1.ViewModels;
using System.Web.Mvc;
using System.Web.Routing;
using SP_ASPNET_1.BusinessLogic;

namespace SP_ASPNET_1.Controllers
{
    [RoutePrefix("Blog")]
    public class BlogPostController : Controller
    {
        private readonly BlogPostOperations _blogPostOperations = new BlogPostOperations();

        [Route("")]
        [HttpGet]
        public ActionResult Index()
        {
            //return this.View();
            BlogIndexViewModel result = this._blogPostOperations.GetBlogIndexViewModel();
            ViewBag.Title = "Blog";
            return this.View(result);
        }


        [Route("Detail/{id:int?}")]
        [HttpGet]
        public ActionResult SinglePost(int? id)
        {
            ViewBag.Title = "single post";

            BlogPost blogPost;

            if (id == null)
            {
                blogPost = this._blogPostOperations.GetLatestBlogPost();
            }
            else
            {
                blogPost = this._blogPostOperations.GetBlogPostByIdD((int)id);
            }

            return View(blogPost);
        }

        [Route("Detail/Random")]
        [HttpGet]
        public ActionResult RandomPost()
        {
            ViewBag.Title = "single post";

            BlogPost blogPost;

            blogPost = this._blogPostOperations.GetRandomBlogPost();

            return View(blogPost);
        }

        [Route("LatestPost")]
        [HttpGet]
        public ActionResult LatestPost()
        {

            BlogPost blogPost;

            blogPost = this._blogPostOperations.GetLatestBlogPost();

            return this.PartialView("~/Views/BlogPost/_BlogPostRecentPartialView.cshtml", blogPost);
        }

        //[Route("Detail/{id:int}")]
        //[HttpGet]
        //public ActionResult Detail(int id)
        //{
        //    BlogPost blogPost = this._blogPostOperations.GetBlogPostByIdD(id);

        //    return View(blogPost);
        //}


        [Route("Create")]
        [HttpPost]
        public ActionResult Create(BlogPost blogPost)
        {
            try
            {
                this._blogPostOperations.Create(blogPost);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Route("Edit/{id:int?}")]
        [HttpGet]
        public ActionResult EditBlogPost(int id)
        {
            BlogPost blogPost;

            blogPost = this._blogPostOperations.GetBlogPostByIdD((int)id);

            return View(blogPost);
        }

        [Route("Edit/{id:int}")]
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Route("Delete/{id:int}")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                this._blogPostOperations.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return this.HttpNotFound();
            }
        }

        //[Route("edit/{id:int}")]
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

SP_ASPNET_1/SP_ASPNET_1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SP_ASPNET_1.DbFiles.Operations;
using SP_ASPNET_1.DbFiles.UnitsOfWork;
using SP_ASPNET_1.ViewModels;

namespace SP_ASPNET_1.Controllers
{
    [RoutePrefix("Home")]
    public class HomeController : Controller
    {
        private HomeOperations _homeOperations = new HomeOperations();

        [Route("~/", Name = "default")]
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [Route("About")]
        [HttpGet]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [Route("Contact")]
        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }

        [Route("Product")]
        [HttpGet]
        public ActionResult Product()
        {
            HomeProductViewModel productLines = _homeOperations.GetHomeProductViewModel();

            return View(productLines);
        }
    }
}

SP_ASPNET_1/SP_ASPNET_1/Views/BlogPost/EditBlogPost.cshtml
@model SP_ASPNET_1.Models.BlogPost

@{
    ViewBag.Title = "EditBlogPost";
}

<h2>EditBlogPost</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogPost</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogPostID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SP_ASPNET_1/SP_ASPNET_1/Views/BlogPost/Index.cshtml
@using SP_ASPNET_1.BusinessLogic
@using SP_ASPNET_1.Models


@{
    Layout = "~/Views/Shared/Blog/_BlogLayout.cshtml";
}
<ul class="Posts__Featured">
    @foreach (BlogPost post in Model.BlogPosts)
    {
        <li class="Posts__Item">
            <img src="@post.ImageUrl" alt="post image preview" class="Post__Image">
            <div class="Post-Preview__Content">
                <h2>@post.Title</h2>
                <p>By @post.Author on @post.DateTime.ToString(Constants.DISPLAY_DATETIME_FORMAT)</p>
                <br>
                <p>@post.Content.Substring(0, 200)...</p>
            </div>
        </li>
        <li class="Posts__Item__Link">
            <button onClick="location.href='@Url.Action("SinglePost", new { id = @post.BlogPostID})'" class="c-btn">read more</button>
            <hr class="Post__Hr" />
        </li>

    }
    <li>
        <button class="c-btn">load more</button>
    </li>
</ul>

SP_ASPNET_1/SP_ASPNET_1/Views/BlogPost/RandomPost.cshtml
@{
    Layout = null;
}

@model SP_ASPNET_1.Models.BlogPost

@Html.Partial("SinglePost", Model)

SP_ASPNET_1/SP_ASPNET_1/Views/BlogPost/SinglePost.cshtml
@using SP_ASPNET_1.BusinessLogic
@model SP_ASPNET_1.Models.BlogPost

@*@{
    ViewBag.Title = "SinglePost";
}*@
@{
    Layout = "~/Views/Shared/Blog/_BlogLayout.cshtml";
}

<div class="SinglePost">
    <img src="@Model.ImageUrl" alt="@Path.GetFileNameWithoutExtension(Model.ImageUrl)" />
    <h2>new chills for summer</h2>
    <p>By @Model.Author on @Model.DateTime.ToString(Constants.DISPLAY_DATETIME_FORMAT)</p>
    <p>
        @Model.Content
    </p>
    <p>
        @Html.ActionLink("Edit", "EditBlogPost", new { id = Model.BlogPostID }) |
        @Html.ActionLink("Back to List", "Index") |
        @Html.ActionLink("Delete", "EditBlogPost", new { id = Model.BlogPostID }) |
    </p>
</div>

SP_ASPNET_1/SP_ASPNET_1/Views/BlogPost/_BlogPostRecentPartialView.cshtml
@using SP_ASPNET_1.BusinessLogic
@model SP_ASPNET_1.Models.BlogPost

<div class="Posts__Recent">
    <img src="@Model.ImageUrl" alt="post image preview" class="Post__Image">
    <div class="Post-Preview__Content">
        <h2>@Model.Title</h2>
        <p>By @Model.Author on @Model.DateTime.ToString(Constants.DISPLAY_DATETIME_FORMAT)</p>
        <br>
        <p>@Model.Content.Substring(0, 50)...</p>
        <button onClick="location.href='@Url.Action("SinglePost", new { id = Model.BlogPostID})'" class="c-btn c-btn--dark">read more</button>
    </div>
</div>

SP_ASPNET_1/SP_ASPNET_1/Views/Home/About.cshtml
<h1 class="text--white">About</h1>
<div class="about__flier" style="background-color: #ebebed;">
    <img class="faded faded-left faded-right" src="/Content/images/bg-header-about.jpg" />
</div>
<div>
    <div class="about">
        <aside>
            <h2>Be Part of Our Community</h2>
            <p>
                Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
            </p>
        </aside>

        <main class="about__content">
            <h2>We Have Free Templates For Everyone</h2>
            <p>Our website templates are created with inspiration, checked for quality and originality and meticulously sliced and coded. What’s more, they’re absolutely free! You can do a lot with them. You can modify them.</p>
            <p>You can use them to design websites for clients, so long as you agree with the <a href="http://www.freewebsitetemplates.com/about/terms/">Terms of Use</a>. You can even remove all our links if you want to.</p>
            <h2>We Have More Templates For You</h2>
            <p>Looking for more templates? Just browse through all our <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a>. But if you can’t find any website templates you can use, try our <a href="http://www.freewebsitetemplates.com/freewebdesign/">Free Web Design</a> service and tell us all about it. We love a good challenge!</p>
            <h2>Template Details</h2>
            <div>Design Version 2.</div>
            <div>Code Version 1.</div>
            <p>Website Template details, discussion and updates for this <a href="http://www.freewebsitetemplates.com/discuss/frozenyogurtshop/">Frozen Yogurt Shop Website Template</a>.</p>
            <p>Website Template design by  <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a>.</p>
        </main>
    </div>
</div>

SP_ASPNET_1/SP_ASPNET_1/Views/Home/Contact.cshtml
<h1 class="text--white">Contact</h1>
<div class="body Contact">
    <div class="Contact__Header">
        <img src="../../Content/images/check-in.png" alt="checkIn arrow"/>
        <div class="Contact__Header__Content">
            <h2>unit 123, abc building, business park</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit debitis eius, unde dolorum beatae voluptatem vel?
            </p>
        </div>
    </div>
    <div class="Contact__Form">
        <form action="" method="post">
            <h2>inquiry form</h2>
            <div class="form-group">
                <input type="text" name="Name" placeholder="Name">
            </div>
            <div class="form-group">
                <input type="text" name="Email" placeholder="Email">
            </div>
            <div class="form-group">
                <input type="text" name="Subject" placeholder="Subject">
            </div>
            <textarea name="meassage" cols="50" rows="7" placeholder="Share your thoughts"></textarea>

            <button type="submit" class="c-btn text--gray" id="submit">Send</button>
        </form>
        <aside>
            <h2>We'd love to hear from you.</h2>
            <p>
                If you're having problems editing this website template, then don't hesitate to ask for help on the
            </p>
        </aside>
    </div>
    @*<form>
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>*@
</div>
<div style="display: flex; justify-content: center; opacity: 0.1; min-height: 300px">
    <div id="image"></div>
</div>
<script>
    function ajax_get(url, callback) {
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function() {
            if (xmlhttp.readyState == 4 && xmlhttp.status === 200) {
                console.log('responseText:' + xmlhttp.responseText);
                try {
                    var data = JSON.parse(xmlhttp.responseText);
                } catch (err) {
                    console.log(err.message + " in " + xmlhttp.responseText);
                    return;
                }
                callback(data);
            }
        };

        xmlhttp.open("GET", url, true);
        xmlhttp.send();
    }

    ajax_get('https://api.thecatapi.com/v1/images/search?size=med&mime_types=gif', function(data) {
        var html = '<img src="' + data[0]["url"] + '">';
        document.getElementById("image").innerHTML = html;
    });
</script>

SP_ASPNET_1/SP_ASPNET_1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main class="body">
    <header class="flier">
        <div class="flier__picture">
            <img src="~/Content/images/bg-home.jpg" alt="" />
            <a href="#">FREEZE DELIGHT</a>
        </div>
    </header>
    <article class="body__article">
        <div>
            <div class="body__article__text-content">
                <h3>NEW PRODUCT</h3>
                <h2>The Twist Of Healthy Yoghurt</h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                    Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel
                    sapien. Integer vulputate sem a nibh rutrum consequat. Nullam eget
                    nisl. Fusce
                </p>
            </div>
            <img src="~/Content/images/yogurt.jpg" alt="" />
        </div>
    </article>
</main>
<div class="home__footer">
    <div class="body">
        <ul>
            <li>
                <a class="product" href="#"></a>
                <h3 class="text--white">Products</h3>
            </li>
            <li>
                <a class="about" href="#"></a>
                <h3 class="text--white">Our Story</h3>
            </li>
            <li>
                <a class="flavour" href="#"></a>
                <h3 class="text--white">Flavours</h3>
            </li>
            <li>
                <a class="contact" href="#"></a>
                <h3 class="text--white">Our Location</h3>
            </li>
        </ul>
    </div>
</div>

SP_ASPNET_1/SP_ASPNET_1/Views/Home/Product.cshtml
@using SP_ASPNET_1.Models
@model SP_ASPNET_1.ViewModels.HomeProductViewModel

<div class="product">
    @foreach (ProductLine productLine in Model.ProductLines)
    {
        <div class="product__edition-lineup">
            <div>
                <h2>@productLine.Title</h2>
                <p>@productLine.Description</p>
            </div>
            @foreach (ProductItem productItem in productLine.ProductItems)
            {
                <div>
                    <img src="@productItem.ImageURL" alt="@productItem.ImageAlt">
                    <h2 class="h2--smaller">@productItem.Title</h2>
                </div>
            } 
        </div>
    }
    @*<div class="product__edition-lineup">
        <div>
            <h2>All Time Classic</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam animi nobis earum, quisquam facere aperiam maiores tempora modi</p>
        </div>
        <div>
            <img src="~/Content/images/products/kiwi.jpg" alt="kiwi icecream">
            <h2 class="h2--smaller">kiwi</h2>
        </div>
        <div>
            <img src="~/Content/images/products/mango.jpg" alt="mango icecream">
            <h2 class="h2--smaller">mango</h2>
        </div>
        <div>
            <img src="~/Content/images/products/cantaloupe.jpg" alt="cantaloupe icecream">
            <h2 class="h2--smaller">cantaloupe</h2>
        </div>
    </div>
    <div class="product__edition-lineup">
        <div>
            <h2>Berry Special</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam animi nobis earum, quisquam facere aperiam maiores tempora modi</p>
        </div>
        <div>
            <img src="~/Content/images/products/blackberry.jpg" alt="blackberry icecream">
            <h2 class="h2--smaller">blackberry</h2>
        </div>
        <div>
            <img src="~/Content/images/products/strawberry.jpg" alt="strawberry icecream">
            <h2 class="h2--smaller">strawberry</h2>
        </div>
        <div>
            <img src="~/Content/images/products/blueberry.jpg" alt="blueberry icecreeam">
            <h2 class="h2--smaller">blueberry</h2>
        </div>
    </div>
    <div class="product__edition-lineup">
        <div>
            <h2>Fruit Blast</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam animi nobis earum, quisquam facere aperiam maiores tempora modi</p>
        </div>
        <div>
            <img src="~/Content/images/products/grapes.jpg" alt="grape icecream">
            <h2 class="h2--smaller">grape</h2>
        </div>
        <div>
            <img src="~/Content/images/products/green-apple.jpg" alt="green apple icecream">
            <h2 class="h2--smaller">green apple</h2>
        </div>
        <div>
            <img src="~/Content/images/products/pineapple.jpg" alt="pineapple icecream">
            <h2 class="h2--smaller">pineapple</h2>
        </div>
    </div>*@

</div>

SP_ASPNET_1/SP_ASPNET_1/Views/Home/SinglePost.cshtml
@{
    ViewBag.Title = "SinglePost";
}

<h2>SinglePost</h2>

SP_ASPNET_1/SP_ASPNET_1/Views/Shared/Blog/_BlogLayout.cshtml
@using SP_ASPNET_1.Models
@using SP_ASPNET_1.BusinessLogic

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="Blog">
    <h1 class="text--white">@ViewBag.Title</h1>
    <div class="Blog__Posts">
        @RenderBody()
        @{
            Html.RenderAction("LatestPost", "BlogPost");
        }
    </div>
</main>

SP_ASPNET_1/SP_ASPNET_1/Views/Shared/_Layout.cshtml
@using SP_ASPNET_1.BusinessLogic

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - School Project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <header class="header">
        <div class="header__navbar">
            <img #logo src="~/Content/images/logo.png" /> <span class="spacer"></span>
            <nav>
                <ul>
                    <li><a href="@Url.Action("Index", "Home")" class="@(@Html.IsActive("Home", "Index"))">HOME</a></li>
                    <li>
                        <a href="@Url.Action("About", "Home")" class="@(@Html.IsActive("Home", "About"))">ABOUT</a>
                        <ul>
                            <li><a href="@Url.Action("Product", "Home")" class="@(@Html.IsActive("Home", "Product"))">PRODUCT</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "BlogPost")" class="@(@Html.IsActive("Blog", "Index"))">BLOG</a>
                        <ul>
                            <li><a href="@Url.Action("RandomPost", "BlogPost")" class="@(@Html.IsActive("Blog", "SinglePost"))">SINGLE POST</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Contact", "Home")" class="@(@Html.IsActive("Home", "Contact"))">CONTACT</a></li>
                </ul>
            </nav>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div>
            <div class="container">
                <div class="social">
                    <a href="#" class="facebook"></a>
                    <a href="#" class="googleplus"></a>
                    <a href="#" class="pinterest"></a> <a href="#" class="twitter"></a>
                </div>
                <p>© 2023 FeelaV. All Rights Nonreserved.</p>
            </div>
        </div>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>